[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pdf2docx>=0.5.8",
    "pdfplumber>=0.11.7",
    "pymupdf>=1.26.3",
    "python-docx>=1.2.0",
]
